site_name: AGS Tween Module
repo_url: https://github.com/edmundito/ags-tween
pages:
  - ['index.md', 'Home']
  - ['getting-started.md', 'Getting Started']
  - ['scripting/enums.md', 'Scripting', 'Enumerated Types']
  - ['scripting/commontweens.md', 'Scripting', 'Common Tweens']
  - ['scripting/audiotweens.md', 'Scripting', 'Audio Tweens']
  - ['scripting/globaltween.md', 'Scripting', 'Global Tween Functions']
  - ['scripting/tween.md', 'Scripting', 'Custom Tweens']
  - ['scripting/globaltiming.md', 'Scripting', 'Timing Utilities']
  - ['scripting/tweengame.md', 'Scripting', 'TweenGame Utilities']
  - ['scripting/tweenmaths.md', 'Scripting', 'TweenMaths Utilities']
  - ['scripting/tweeneasing.md', 'Scripting', 'TweenEasing Equations']
  - ['scripting/settings.md', 'Scripting', 'Settings']
