site_name: AGS Tween Module
repo_url: https://github.com/edmundito/ags-tween
pages:
  - ['index.md', 'Home']
  - ['getting-started.md', 'Getting Started']
  - ['enumerated-types.md', 'API', 'Enumerated Types']
