site_name: AGS Tween Module
repo_url: https://github.com/edmundito/ags-tween
pages:
  - ['index.md', 'Home']
  - ['getting-started.md', 'Getting Started']
  - ['scripting/enums.md', 'Scripting', 'Enumerated Types']
  - ['scripting/globaltiming.md', 'Scripting', 'Global Timing Functions']
  - ['scripting/tween.md', 'Scripting', 'Tween']
  - ['scripting/tweengame.md', 'Scripting', 'TweenGame']
  - ['scripting/tweenmaths.md', 'Scripting', 'TweenMaths']
